"""explain-changes — Produces a plain-English summary of every change made and why."""

SKILL_NAME = "explain-changes"
SKILL_DESCRIPTION = "Produces a plain-English summary of every change made and why."


def execute(html: str, report: dict, changes: list[str] | None = None) -> dict:
    if changes is None:
        changes = []
    if not changes:
        return {
            "changes": [],
            "summary": "No changes were needed.",
            "modified_html": html,
            "target": "full",
        }

    score = report.get("overall_score", "N/A")
    grade = report.get("grade", "N/A")
    url = report.get("url", "the site")

    lines = [
        f"# AI Readiness Improvements for {url}",
        "",
        f"**Original Score:** {score}/100 (Grade {grade})",
        "",
        "## Changes Made",
        "",
    ]
    for i, change in enumerate(changes, 1):
        lines.append(f"{i}. {change}")
    lines.append("")
    lines.append("## Why These Changes Help")
    lines.append("")
    lines.append(
        "These changes improve how AI search engines (ChatGPT, Perplexity, "
        "Claude, Google AI Overviews) discover, understand, and cite your "
        "content. Structured data helps AI extract facts. Clear headings "
        "improve content navigation. Readable text and Q&A sections make "
        "your content more likely to be quoted in AI-generated answers."
    )
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [AI Readiness Checker](https://github.com) v2*")

    summary = "\n".join(lines)

    return {
        "changes": changes,
        "summary": summary,
        "modified_html": html,
        "target": "full",
    }
