"""fix-llms-txt — Generates a valid llms.txt file from page content."""

import re

SKILL_NAME = "fix-llms-txt"
SKILL_DESCRIPTION = "Generates a valid llms.txt file based on page content."


def execute(html: str, report: dict) -> dict:
    llms_info = report.get("modules", {}).get("llms_txt", {})
    if llms_info.get("score", 1.0) > 0.0 and llms_info.get("details", {}).get("found"):
        return {"changes": [], "modified_html": html, "target": "full"}

    title = _extract_title(html)
    h1 = _extract_first_h1(html)
    description = _extract_description(html)
    url = report.get("url", "https://example.com")

    llms_content = f"""# {title or h1 or 'Website'}
> {description or 'Website content overview'}

## Main Content
- {h1 or 'Home'}
{_extract_section_links(html)}

## About
This llms.txt file was auto-generated to help AI systems understand and cite this site's content.
Generated by: AI Readiness Checker (v2)
"""

    return {
        "changes": [f"Generated llms.txt ({len(llms_content)} chars) for {url}"],
        "modified_html": html,
        "target": "full",
    }


def _extract_title(html: str) -> str | None:
    m = re.search(r"<title[^>]*>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def _extract_first_h1(html: str) -> str | None:
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def _extract_description(html: str) -> str | None:
    m = re.search(
        r'<meta\s+name="description"\s+content="([^"]*)"',
        html,
        re.IGNORECASE,
    )
    return m.group(1).strip() if m else None


def _extract_section_links(html: str) -> str:
    h2s = re.findall(r"<h2[^>]*>(.*?)</h2>", html, re.IGNORECASE | re.DOTALL)
    if not h2s:
        return "- [Page content](.)"
    return "\n".join(f"- [{h.strip()}](.)" for h in h2s[:10])
