"""fix-llms-txt — Generates a valid llms.txt file from page content.

When an LLM backend is provided (v3), uses the LLM to generate a proper
llms.txt with real content summaries. Otherwise falls back to regex-based
scraping of titles and headings (v2).
"""

import re

SKILL_NAME = "fix-llms-txt"
SKILL_DESCRIPTION = "Generates a valid llms.txt file based on page content."


def execute(html: str, report: dict, backend=None) -> dict:
    llms_info = report.get("modules", {}).get("llms_txt", {})
    if llms_info.get("score", 1.0) > 0.0 and llms_info.get("details", {}).get("found"):
        return {"changes": [], "modified_html": html, "target": "full"}

    url = report.get("url", "https://example.com")

    if backend is not None:
        return _generate_with_llm(html, url, backend)

    # v2 fallback: regex-based extraction
    title = _extract_title(html)
    h1 = _extract_first_h1(html)
    description = _extract_description(html)

    llms_content = f"""# {title or h1 or 'Website'}
> {description or 'Website content overview'}

## Main Content
- {h1 or 'Home'}
{_extract_section_links(html)}

## About
This llms.txt file was auto-generated to help AI systems understand and cite this site's content.
Generated by: AI Readiness Checker (v2)
"""

    return {
        "changes": [f"Generated llms.txt ({len(llms_content)} chars) for {url}"],
        "modified_html": html,
        "target": "full",
    }


def _generate_with_llm(html: str, url: str, backend) -> dict:
    """Use LLM to generate a proper llms.txt from page content."""
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html, "lxml")

    title_tag = soup.find("title")
    page_title = title_tag.get_text(strip=True) if title_tag else ""

    meta_desc = soup.find("meta", attrs={"name": "description"})
    description = meta_desc.get("content", "").strip() if meta_desc else ""

    # Extract headings and links for context
    headings = []
    for tag in soup.find_all(["h1", "h2", "h3"]):
        text = tag.get_text(strip=True)
        if text:
            headings.append(f"<{tag.name}>{text}</{tag.name}>")

    links = []
    for a in soup.find_all("a", href=True):
        text = a.get_text(strip=True)
        href = a["href"]
        if text and not href.startswith("#") and not href.startswith("javascript:"):
            links.append(f"- [{text}]({href})")

    heading_text = "\n".join(headings[:20])
    link_text = "\n".join(links[:15])
    body = soup.find("body")
    body_text = body.get_text(separator=" ", strip=True)[:1000] if body else ""

    prompt = f"""Generate a valid llms.txt file for this website.

llms.txt format specification (from llmstxt.org):
- Starts with "# {page_title or 'Website Name'}"
- Optional "> description" blockquote
- "## Section Name" for each content section
- "- [Link text](URL)" for each relevant page/link
- Brief summaries under sections explaining what AI will find there

Website URL: {url}
Page title: {page_title}
Meta description: {description}

Page headings:
{heading_text}

Key links:
{link_text}

Content snippet:
{body_text[:500]}

Generate a complete llms.txt that helps AI systems understand and cite this website.
Use real information from the headings and links above.
Output ONLY the llms.txt content, no explanations."""

    system = (
        "You generate llms.txt files that help AI systems understand websites. "
        "Follow the llmstxt.org specification. Use real content from the provided "
        "headings and links. Output only the markdown content."
    )

    try:
        llms_content = backend.generate(prompt, system=system).strip()
        if llms_content and len(llms_content) > 50:
            return {
                "changes": [
                    f"Generated AI-powered llms.txt ({len(llms_content)} chars) for {url}"
                ],
                "modified_html": html,
                "target": "full",
            }
    except Exception:
        pass

    return {"changes": [], "modified_html": html, "target": "full"}


# ---- v2 regex helpers ----

def _extract_title(html: str) -> str | None:
    m = re.search(r"<title[^>]*>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def _extract_first_h1(html: str) -> str | None:
    m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else None


def _extract_description(html: str) -> str | None:
    m = re.search(
        r'<meta\s+name="description"\s+content="([^"]*)"',
        html,
        re.IGNORECASE,
    )
    return m.group(1).strip() if m else None


def _extract_section_links(html: str) -> str:
    h2s = re.findall(r"<h2[^>]*>(.*?)</h2>", html, re.IGNORECASE | re.DOTALL)
    if not h2s:
        return "- [Page content](.)"
    return "\n".join(f"- [{h.strip()}](.)" for h in h2s[:10])
